name       : ibus
version    : 1.5.13
release    : 6
source     :
    - https://github.com/ibus/ibus/releases/download/1.5.13/ibus-1.5.13.tar.gz : ed73d80542dfdcca190b7958431048cd6830c2ce25c467384630b6a7e957a5f1
license    :
    - LGPL-2.0
summary    : Intelligent Input Bus
builddeps  :
    - pkgconfig(gtk+-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(dconf)
    - pkgconfig(gconf-2.0)
    - pkgconfig(libnotify)
    - vala
description: |
    IBus is an Intelligent Input Bus. It is a new input framework for Linux OS. It provides full featured and user friendly input method user interface.
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
