name       : ibus
version    : 1.5.22
release    : 19
source     :
    - git|https://github.com/ibus/ibus.git : 1.5.22
license    : LGPL-2.0-only
component  : desktop.core
summary    : Intelligent Input Bus
description: |
    IBus is an Intelligent Input Bus. It is a new input framework for Linux OS. It provides full featured and user friendly input method user interface.
builddeps  :
    - pkgconfig(dconf)
    - pkgconfig(gconf-2.0)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libnotify)
    - gnome-common
    - gtk-doc
    - unicode-character-database
    - vala
rundeps    :
    - unicode-character-database
setup      : |
    %patch -p1 < $pkgfiles/0001-Ensure-we-use-the-system-keyboard-layout.patch
    %patch -p1 < $pkgfiles/0001-Do-not-check-for-dbus-launch.patch
    %patch -p1 < $pkgfiles/Fix-arguments-in-GLib-DBusSignalCallback.patch
    %autogen
    %configure --disable-static \
        --enable-gtk-doc \
        --enable-wayland
build      : |
    %make
install    : |
    %make_install
