name       : ibus
version    : 1.5.18
release    : 12
source     :
    - https://github.com/ibus/ibus/releases/download/1.5.18/ibus-1.5.18.tar.gz : 8551f7d027fb65d48225642fc8f3b232412ea75a4eb375244dd72a4d73c2639e
license    : LGPL-2.0-only
component  : desktop.core
summary    : Intelligent Input Bus
description: |
    IBus is an Intelligent Input Bus. It is a new input framework for Linux OS. It provides full featured and user friendly input method user interface.
builddeps  :
    - pkgconfig(dconf)
    - pkgconfig(gconf-2.0)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libnotify)
    - unicode-character-database
    - vala
rundeps    :
    - unicode-character-database
setup      : |
    %patch -p1 < $pkgfiles/0001-Ensure-we-use-the-system-keyboard-layout.patch
    %configure --disable-static --disable-emoji-dict
build      : |
    %make
install    : |
    %make_install
