name       : ibus
version    : 1.5.19
release    : 13
source     :
    - https://github.com/ibus/ibus/releases/download/1.5.19/ibus-1.5.19.tar.gz : 4b66c798dab093f0fa738e5c10688d395a463287d13678c208a81051af5d2429
license    : LGPL-2.0-only
component  : desktop.core
summary    : Intelligent Input Bus
description: |
    IBus is an Intelligent Input Bus. It is a new input framework for Linux OS. It provides full featured and user friendly input method user interface.
builddeps  :
    - pkgconfig(dconf)
    - pkgconfig(gconf-2.0)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libnotify)
    - unicode-character-database
    - vala
rundeps    :
    - unicode-character-database
setup      : |
    %patch -p1 < $pkgfiles/0001-Ensure-we-use-the-system-keyboard-layout.patch
    %configure --disable-static --disable-emoji-dict
build      : |
    %make
install    : |
    %make_install
