name       : ibus
version    : 1.5.28
release    : 25
source     :
    - https://github.com/ibus/ibus/releases/download/1.5.28/ibus-1.5.28.tar.gz : 6c9ff3a7576c3d61264f386030f47ee467eb7298c8104367002986e008765667
license    : LGPL-2.0-only
component  : desktop.core
summary    : Intelligent Input Bus
description: |
    IBus is an Intelligent Input Bus. It is a new input framework for Linux OS. It provides full featured and user friendly input method user interface.
builddeps  :
    - pkgconfig(dconf)
    - pkgconfig(gconf-2.0)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gtk4)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libnotify)
    - gnome-common
    - gtk-doc
    - unicode-character-database
    - vala
rundeps    :
    - unicode-character-database
setup      : |
    %patch -p1 < $pkgfiles/0001-Do-not-check-for-dbus-launch.patch
    %patch -p1 < $pkgfiles/7c8abbe8.patch
    %patch -p1 < $pkgfiles/497f0c74.patch
    %configure --disable-static \
        --enable-gtk4 \
        --enable-gtk-doc \
        --enable-wayland
build      : |
    %make
install    : |
    %make_install
