name       : ibus
version    : 1.5.14
release    : 9
source     :
    - https://github.com/ibus/ibus/releases/download/1.5.14/ibus-1.5.14.tar.gz : a42b40fe4642f36bf2a6f0b4649f54f4043812d6bfee4faca38117799a009d3c
license    : LGPL-2.0
component  : desktop.core
summary    : Intelligent Input Bus
description: |
    IBus is an Intelligent Input Bus. It is a new input framework for Linux OS. It provides full featured and user friendly input method user interface.
builddeps  :
    - pkgconfig(dconf)
    - pkgconfig(gconf-2.0)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libnotify)
    - vala
setup      : |
    %patch -p1 < $pkgfiles/0001-data-Ensure-the-system-layout-is-always-respected.patch
    %configure --disable-static --disable-emoji-dict
build      : |
    %make
install    : |
    %make_install
