name        : ibus
version     : 1.5.11
release     : 5
source     :
    - https://github.com/ibus/ibus/releases/download/1.5.11/ibus-1.5.11.tar.gz : 49995a298a39a137e65c6ee77811b030850ff344b875f29d4ed088f623a546bc
license     :
    - LGPL-2.0
summary     : Intelligent Input Bus
builddeps   :
    - pkgconfig(gtk+-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(dconf)
    - pkgconfig(gconf-2.0)
    - pkgconfig(libnotify)
    - vala
description : |
    IBus is an Intelligent Input Bus. It is a new input framework for Linux OS. It provides full featured and user friendly input method user interface.
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
